baseURL = 'https://lin.foo/'
theme = 'LoveIt'
title = "Welcome to Yuyuan's site"

[author]
  name = "Yuyuan Lin"
  email = "yuyuan@lin.foo"
  link = "https://lin.foo"

enableEmoji = true

[params]
  defaultTheme = "auto"
  description = "Welcome to Yuyuan's site."
  
[params.app]
  svgFavicon = "favicon.svg"
  title = "Yuyuan's site"

[params.home]
  [params.home.posts]
      enable = false
  [params.home.profile]
    enable = true
    avatarUrl = "/img/lin_avatar.png"
    title = ""
    subtitle = "Welcome to Yuyuan's site, while it's still under construction."
    

# Header config
[params.header]
  # desktop header mode ["fixed", "normal", "auto"]
  desktopMode = "fixed"
  # mobile header mode ["fixed", "normal", "auto"]
  mobileMode = "auto"
  [params.header.title]
    # URL of the LOGO
    logo = "/img/lin_logo.png"
    # title name
    name = "Yuyuan's site"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false
    
# footer config
[params.footer]
  enable = true
  hugo = false
  author = true
  since = 2023

# multi languages
languageCode = "en"
languageName = "English"
hasCJKLanguage = true

[menu]
  [[menu.main]]
    weight = 1
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "分类"
  [[menu.main]]
    weight = 2
    identifier = "Recipes"
    pre = ""
    post = ""
    name = "Recipes"
    url = "/categories/recipes/"
    title = "食单"
  [[menu.main]]
    weight = 4
    identifier = "podcasts"
    pre = ""
    post = ""
    name = "Podcasts"
    url = "/podcasts/"
    title = "播客"
  [[menu.main]]
    weight = 5
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = "关于我"
    
    
[params.search]
  enable = true
  # type of search engine ["lunr", "algolia"]
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = "Search for contents..."
  # LoveIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # LoveIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
    
# global share setting
[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = false
  Whatsapp = true
  HackerNews = false
  Line = true
  Weibo = true
