baseURL = 'https://lin.foo/'
theme = 'LoveIt'
title = "Welcome to Yuyuan's site"

[author]
  name = "Yuyuan Lin"
  email = "yuyuan@lin.foo"
  link = "https://lin.foo"

enableEmoji = true

[params]
  defaultTheme = "auto"
  description = "Welcome to Yuyuan's site."
  
[params.app]
  svgFavicon = "favicon.svg"
  title = "Yuyuan's site"

[params.home]
  [params.home.profile]
    enable = true
    avatarUrl = "/img/lin_avatar.png"
    title = ""
    subtitle = "Welcome to Yuyuan's site, while it's still under construction."
    

# Header config
[params.header]
  # desktop header mode ["fixed", "normal", "auto"]
  desktopMode = "fixed"
  # mobile header mode ["fixed", "normal", "auto"]
  mobileMode = "auto"
  [params.header.title]
    # URL of the LOGO
    logo = "/img/lin_logo.png"
    # title name
    name = "Yuyuan's site"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false
    
# footer config
[params.footer]
  enable = true
  hugo = false
  author = true
  since = 2023

# multi languages
languageCode = "en"
languageName = "English"
hasCJKLanguage = true

[menu]
  [[menu.main]]
    weight = 1
    identifier = "podcasts"
    pre = ""
    post = ""
    name = "Podcasts"
    url = "/podcasts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    